// Code generated by BarefootJS. DO NOT EDIT.
package main

import "math/rand"

// randomID generates a random string of length n for ScopeID.
func randomID(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

// =============================================================================
// Manual Types (application-specific, not generated from components)
// =============================================================================

// Todo represents a single todo item.
type Todo struct {
	ID      int    `json:"id"`
	Text    string `json:"text"`
	Done    bool   `json:"done"`
	Editing bool   `json:"editing"`
}

// CounterInput is the user-facing input type.
type CounterInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Initial int
}

// CounterProps is the props type for the Counter component.
type CounterProps struct {
	ScopeID string `json:"scopeID"`
	Initial int `json:"initial"`
	Count int `json:"count"`
	Doubled int `json:"doubled"`
}

// NewCounterProps creates CounterProps from CounterInput.
func NewCounterProps(in CounterInput) CounterProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Counter_" + randomID(6)
	}

	return CounterProps{
		ScopeID: scopeID,
		Initial: in.Initial,
		Count: in.Initial,
		Doubled: in.Initial * 2,
	}
}

// ToggleItemInput is the user-facing input type.
type ToggleItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Label interface{}
	DefaultOn bool
}

// ToggleItemProps is the props type for the ToggleItem component.
type ToggleItemProps struct {
	ScopeID string `json:"scopeID"`
	Label interface{} `json:"label"`
	DefaultOn bool `json:"defaultOn"`
	On bool `json:"on"`
}

// NewToggleItemProps creates ToggleItemProps from ToggleItemInput.
func NewToggleItemProps(in ToggleItemInput) ToggleItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ToggleItem_" + randomID(6)
	}

	return ToggleItemProps{
		ScopeID: scopeID,
		Label: in.Label,
		DefaultOn: in.DefaultOn,
		On: in.DefaultOn,
	}
}

// ToggleInput is the user-facing input type.
type ToggleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	ToggleItems []ToggleItemInput
}

// ToggleProps is the props type for the Toggle component.
type ToggleProps struct {
	ScopeID string `json:"scopeID"`
	ToggleItems []ToggleItemProps `json:"toggleItems"`
}

// NewToggleProps creates ToggleProps from ToggleInput.
func NewToggleProps(in ToggleInput) ToggleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Toggle_" + randomID(6)
	}

	toggleItems := make([]ToggleItemProps, len(in.ToggleItems))
	for i, item := range in.ToggleItems {
		toggleItems[i] = NewToggleItemProps(item)
	}

	return ToggleProps{
		ScopeID: scopeID,
		ToggleItems: toggleItems,
	}
}

// FizzBuzzCounterInput is the user-facing input type.
type FizzBuzzCounterInput struct {
	ScopeID string // Optional: if empty, random ID is generated
}

// FizzBuzzCounterProps is the props type for the FizzBuzzCounter component.
type FizzBuzzCounterProps struct {
	ScopeID string `json:"scopeID"`
	Count int `json:"count"`
	ShowDetails bool `json:"showDetails"`
	Doubled int `json:"doubled"`
}

// NewFizzBuzzCounterProps creates FizzBuzzCounterProps from FizzBuzzCounterInput.
func NewFizzBuzzCounterProps(in FizzBuzzCounterInput) FizzBuzzCounterProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "FizzBuzzCounter_" + randomID(6)
	}

	return FizzBuzzCounterProps{
		ScopeID: scopeID,
		Count: 0,
		ShowDetails: false,
		Doubled: 0 * 2,
	}
}

// DashboardInput is the user-facing input type.
type DashboardInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	ShowCounter bool
	ShowMessage bool
	InitialCount int
	Message string
}

// DashboardProps is the props type for the Dashboard component.
type DashboardProps struct {
	ScopeID string `json:"scopeID"`
	ShowCounter bool `json:"showCounter"`
	ShowMessage bool `json:"showMessage"`
	InitialCount int `json:"initialCount"`
	Message string `json:"message"`
	Count int `json:"count"`
	Text string `json:"text"`
}

// NewDashboardProps creates DashboardProps from DashboardInput.
func NewDashboardProps(in DashboardInput) DashboardProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Dashboard_" + randomID(6)
	}

	return DashboardProps{
		ScopeID: scopeID,
		ShowCounter: in.ShowCounter,
		ShowMessage: in.ShowMessage,
		InitialCount: in.InitialCount,
		Message: in.Message,
		Count: in.InitialCount,
		Text: in.Message,
	}
}

// TodoItemInput is the user-facing input type.
type TodoItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Todo Todo
	OnToggle interface{}
	OnDelete interface{}
	OnStartEdit interface{}
	OnFinishEdit interface{}
}

// TodoItemProps is the props type for the TodoItem component.
type TodoItemProps struct {
	ScopeID string `json:"scopeID"`
	Todo Todo `json:"todo"`
	OnToggle interface{} `json:"onToggle"`
	OnDelete interface{} `json:"onDelete"`
	OnStartEdit interface{} `json:"onStartEdit"`
	OnFinishEdit interface{} `json:"onFinishEdit"`
}

// NewTodoItemProps creates TodoItemProps from TodoItemInput.
func NewTodoItemProps(in TodoItemInput) TodoItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoItem_" + randomID(6)
	}

	return TodoItemProps{
		ScopeID: scopeID,
		Todo: in.Todo,
		OnToggle: in.OnToggle,
		OnDelete: in.OnDelete,
		OnStartEdit: in.OnStartEdit,
		OnFinishEdit: in.OnFinishEdit,
	}
}

// AddTodoFormInput is the user-facing input type.
type AddTodoFormInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	OnAdd interface{}
}

// AddTodoFormProps is the props type for the AddTodoForm component.
type AddTodoFormProps struct {
	ScopeID string `json:"scopeID"`
	OnAdd interface{} `json:"onAdd"`
	NewText string `json:"newText"`
}

// NewAddTodoFormProps creates AddTodoFormProps from AddTodoFormInput.
func NewAddTodoFormProps(in AddTodoFormInput) AddTodoFormProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "AddTodoForm_" + randomID(6)
	}

	return AddTodoFormProps{
		ScopeID: scopeID,
		OnAdd: in.OnAdd,
		NewText: "",
	}
}

// TodoAppInput is the user-facing input type.
type TodoAppInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	InitialTodos []Todo
}

// TodoAppProps is the props type for the TodoApp component.
type TodoAppProps struct {
	ScopeID string `json:"scopeID"`
	InitialTodos []Todo `json:"initialTodos"`
	Todos []Todo `json:"todos"`
	TodoItems    []TodoItemProps  `json:"-"`         // For Go template (not in JSON)
	DoneCount    int              `json:"doneCount"` // Pre-computed done count
	AddTodoForm  AddTodoFormProps `json:"addTodoForm"`
}

// NewTodoAppProps creates TodoAppProps from TodoAppInput.
func NewTodoAppProps(in TodoAppInput) TodoAppProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoApp_" + randomID(6)
	}

	return TodoAppProps{
		ScopeID: scopeID,
		InitialTodos: in.InitialTodos,
		Todos: nil,
	}
}
