// Code generated by BarefootJS. DO NOT EDIT.
package main

import (
	"math/rand"

	bf "github.com/barefootjs/runtime/bf"
)

// randomID generates a random string of length n for ScopeID.
func randomID(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

// =============================================================================
// Manual Types (application-specific, not generated from components)
// =============================================================================

// Todo represents a single todo item.
type Todo struct {
	ID      int    `json:"id"`
	Text    string `json:"text"`
	Done    bool   `json:"done"`
	Editing bool   `json:"editing"`
}

// CounterInput is the user-facing input type.
type CounterInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Initial int
}

// CounterProps is the props type for the Counter component.
type CounterProps struct {
	ScopeID string `json:"scopeID"`
	Scripts *bf.ScriptCollector `json:"-"`
	Initial int `json:"initial"`
	Count int `json:"count"`
	Doubled int `json:"doubled"`
}

// NewCounterProps creates CounterProps from CounterInput.
func NewCounterProps(in CounterInput) CounterProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Counter_" + randomID(6)
	}

	return CounterProps{
		ScopeID: scopeID,
		Initial: in.Initial,
		Count: in.Initial,
		Doubled: in.Initial * 2,
	}
}

// ToggleItemInput is the user-facing input type.
type ToggleItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Label interface{}
	DefaultOn bool
}

// ToggleItemProps is the props type for the ToggleItem component.
type ToggleItemProps struct {
	ScopeID string `json:"scopeID"`
	Scripts *bf.ScriptCollector `json:"-"`
	Label interface{} `json:"label"`
	DefaultOn bool `json:"defaultOn"`
	On bool `json:"on"`
}

// NewToggleItemProps creates ToggleItemProps from ToggleItemInput.
func NewToggleItemProps(in ToggleItemInput) ToggleItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ToggleItem_" + randomID(6)
	}

	return ToggleItemProps{
		ScopeID: scopeID,
		Label: in.Label,
		DefaultOn: in.DefaultOn,
		On: in.DefaultOn,
	}
}

// ToggleInput is the user-facing input type.
type ToggleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	ToggleItems []ToggleItemInput
}

// ToggleProps is the props type for the Toggle component.
type ToggleProps struct {
	ScopeID string `json:"scopeID"`
	Scripts *bf.ScriptCollector `json:"-"`
	ToggleItems []ToggleItemProps `json:"toggleItems"`
}

// NewToggleProps creates ToggleProps from ToggleInput.
func NewToggleProps(in ToggleInput) ToggleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Toggle_" + randomID(6)
	}

	toggleItems := make([]ToggleItemProps, len(in.ToggleItems))
	for i, item := range in.ToggleItems {
		toggleItems[i] = NewToggleItemProps(item)
	}

	return ToggleProps{
		ScopeID: scopeID,
		ToggleItems: toggleItems,
	}
}

// TodoItemInput is the user-facing input type.
type TodoItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Todo Todo
	OnToggle interface{}
	OnDelete interface{}
	OnStartEdit interface{}
	OnFinishEdit interface{}
}

// TodoItemProps is the props type for the TodoItem component.
type TodoItemProps struct {
	ScopeID string `json:"scopeID"`
	Scripts *bf.ScriptCollector `json:"-"`
	Todo Todo `json:"todo"`
	OnToggle interface{} `json:"onToggle"`
	OnDelete interface{} `json:"onDelete"`
	OnStartEdit interface{} `json:"onStartEdit"`
	OnFinishEdit interface{} `json:"onFinishEdit"`
}

// NewTodoItemProps creates TodoItemProps from TodoItemInput.
func NewTodoItemProps(in TodoItemInput) TodoItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoItem_" + randomID(6)
	}

	return TodoItemProps{
		ScopeID: scopeID,
		Todo: in.Todo,
		OnToggle: in.OnToggle,
		OnDelete: in.OnDelete,
		OnStartEdit: in.OnStartEdit,
		OnFinishEdit: in.OnFinishEdit,
	}
}

// TodoAppInput is the user-facing input type.
type TodoAppInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	InitialTodos []Todo
}

// TodoAppProps is the props type for the TodoApp component.
type TodoAppProps struct {
	ScopeID string `json:"scopeID"`
	Scripts *bf.ScriptCollector `json:"-"`
	InitialTodos []Todo `json:"initialTodos"`
	Todos []Todo `json:"todos"`
	NewText string `json:"newText"`
	Filter string `json:"filter"`
	TodoItems    []TodoItemProps  `json:"-"`         // For Go template (not in JSON)
	DoneCount    int              `json:"doneCount"` // Pre-computed done count
}

// NewTodoAppProps creates TodoAppProps from TodoAppInput.
func NewTodoAppProps(in TodoAppInput) TodoAppProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoApp_" + randomID(6)
	}

	return TodoAppProps{
		ScopeID: scopeID,
		InitialTodos: in.InitialTodos,
		Todos: nil,
		NewText: "",
		Filter: "all",
	}
}

// TodoAppSSRInput is the user-facing input type.
type TodoAppSSRInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	InitialTodos []Todo
}

// TodoAppSSRProps is the props type for the TodoAppSSR component.
type TodoAppSSRProps struct {
	ScopeID string `json:"scopeID"`
	Scripts *bf.ScriptCollector `json:"-"`
	InitialTodos []Todo `json:"initialTodos"`
	Todos []Todo `json:"todos"`
	NewText string `json:"newText"`
	Filter string `json:"filter"`
	TodoItems    []TodoItemProps  `json:"-"`         // For Go template (not in JSON)
	DoneCount    int              `json:"doneCount"` // Pre-computed done count
}

// NewTodoAppSSRProps creates TodoAppSSRProps from TodoAppSSRInput.
func NewTodoAppSSRProps(in TodoAppSSRInput) TodoAppSSRProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoAppSSR_" + randomID(6)
	}

	return TodoAppSSRProps{
		ScopeID: scopeID,
		InitialTodos: in.InitialTodos,
		Todos: nil,
		NewText: "",
		Filter: "all",
	}
}

// ReactiveChildInput is the user-facing input type.
type ReactiveChildInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Value interface{}
	Label interface{}
	OnIncrement interface{}
}

// ReactiveChildProps is the props type for the ReactiveChild component.
type ReactiveChildProps struct {
	ScopeID string `json:"scopeID"`
	Scripts *bf.ScriptCollector `json:"-"`
	Value interface{} `json:"value"`
	Label interface{} `json:"label"`
	OnIncrement interface{} `json:"onIncrement"`
}

// NewReactiveChildProps creates ReactiveChildProps from ReactiveChildInput.
func NewReactiveChildProps(in ReactiveChildInput) ReactiveChildProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ReactiveChild_" + randomID(6)
	}

	return ReactiveChildProps{
		ScopeID: scopeID,
		Value: in.Value,
		Label: in.Label,
		OnIncrement: in.OnIncrement,
	}
}

// ReactivePropsInput is the user-facing input type.
type ReactivePropsInput struct {
	ScopeID string // Optional: if empty, random ID is generated
}

// ReactivePropsProps is the props type for the ReactiveProps component.
type ReactivePropsProps struct {
	ScopeID string `json:"scopeID"`
	Scripts *bf.ScriptCollector `json:"-"`
	Count int `json:"count"`
	Doubled int `json:"doubled"`
	ReactiveChildA ReactiveChildProps  `json:"-"` // For Go template (Child A)
	ReactiveChildB ReactiveChildProps  `json:"-"` // For Go template (Child B)
}

// NewReactivePropsProps creates ReactivePropsProps from ReactivePropsInput.
func NewReactivePropsProps(in ReactivePropsInput) ReactivePropsProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ReactiveProps_" + randomID(6)
	}

	return ReactivePropsProps{
		ScopeID: scopeID,
		Count:   0,
		Doubled: 0,
		ReactiveChildA: NewReactiveChildProps(ReactiveChildInput{
			ScopeID: scopeID + "_slot_6",
			Value:   0,
			Label:   "Child A",
		}),
		ReactiveChildB: NewReactiveChildProps(ReactiveChildInput{
			ScopeID: scopeID + "_slot_7",
			Value:   0,
			Label:   "Child B (doubled)",
		}),
	}
}
