// Code generated by BarefootJS. DO NOT EDIT.
package main

import "math/rand"

// randomID generates a random string of length n for ScopeID.
func randomID(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

// =============================================================================
// Manual Types (application-specific, not generated from components)
// =============================================================================

// Todo represents a single todo item.
type Todo struct {
	ID      int    `json:"id"`
	Text    string `json:"text"`
	Done    bool   `json:"done"`
	Editing bool   `json:"editing"`
}

// CounterInput is the user-facing input type.
type CounterInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Initial int
}

// CounterProps is the props type for the Counter component.
type CounterProps struct {
	ScopeID string `json:"scopeID"`
	Initial int `json:"initial"`
	Count int `json:"count"`
	Doubled int `json:"doubled"`
}

// NewCounterProps creates CounterProps from CounterInput.
func NewCounterProps(in CounterInput) CounterProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Counter_" + randomID(6)
	}

	return CounterProps{
		ScopeID: scopeID,
		Initial: in.Initial,
		Count: in.Initial,
		Doubled: in.Initial * 2,
	}
}

// ToggleItemInput is the user-facing input type.
type ToggleItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Label interface{}
	DefaultOn bool
}

// ToggleItemProps is the props type for the ToggleItem component.
type ToggleItemProps struct {
	ScopeID string `json:"scopeID"`
	Label interface{} `json:"label"`
	DefaultOn bool `json:"defaultOn"`
	On bool `json:"on"`
}

// NewToggleItemProps creates ToggleItemProps from ToggleItemInput.
func NewToggleItemProps(in ToggleItemInput) ToggleItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ToggleItem_" + randomID(6)
	}

	return ToggleItemProps{
		ScopeID: scopeID,
		Label: in.Label,
		DefaultOn: in.DefaultOn,
		On: in.DefaultOn,
	}
}

// ToggleInput is the user-facing input type.
type ToggleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	ToggleItems []ToggleItemInput
}

// ToggleProps is the props type for the Toggle component.
type ToggleProps struct {
	ScopeID string `json:"scopeID"`
	ToggleItems []ToggleItemProps `json:"toggleItems"`
}

// NewToggleProps creates ToggleProps from ToggleInput.
func NewToggleProps(in ToggleInput) ToggleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Toggle_" + randomID(6)
	}

	toggleItems := make([]ToggleItemProps, len(in.ToggleItems))
	for i, item := range in.ToggleItems {
		toggleItems[i] = NewToggleItemProps(item)
	}

	return ToggleProps{
		ScopeID: scopeID,
		ToggleItems: toggleItems,
	}
}

// TodoItemInput is the user-facing input type.
type TodoItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	Todo Todo
	OnToggle interface{}
	OnDelete interface{}
	OnStartEdit interface{}
	OnFinishEdit interface{}
}

// TodoItemProps is the props type for the TodoItem component.
type TodoItemProps struct {
	ScopeID string `json:"scopeID"`
	Todo Todo `json:"todo"`
	OnToggle interface{} `json:"onToggle"`
	OnDelete interface{} `json:"onDelete"`
	OnStartEdit interface{} `json:"onStartEdit"`
	OnFinishEdit interface{} `json:"onFinishEdit"`
}

// NewTodoItemProps creates TodoItemProps from TodoItemInput.
func NewTodoItemProps(in TodoItemInput) TodoItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoItem_" + randomID(6)
	}

	return TodoItemProps{
		ScopeID: scopeID,
		Todo: in.Todo,
		OnToggle: in.OnToggle,
		OnDelete: in.OnDelete,
		OnStartEdit: in.OnStartEdit,
		OnFinishEdit: in.OnFinishEdit,
	}
}

// TodoAppInput is the user-facing input type.
type TodoAppInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	InitialTodos []Todo
}

// TodoAppProps is the props type for the TodoApp component.
type TodoAppProps struct {
	ScopeID string `json:"scopeID"`
	InitialTodos []Todo `json:"initialTodos"`
	Todos []Todo `json:"todos"`
	NewText string `json:"newText"`
	Filter string `json:"filter"`
	HashListenerAdded bool `json:"hashListenerAdded"`
	TodoItems      []TodoItemProps  `json:"-"`              // For Go template (not in JSON)
	DoneCount      int              `json:"doneCount"`      // Pre-computed done count
	HasTodos       bool             `json:"-"`              // len(todos) > 0
	AllDone        bool             `json:"-"`              // all todos done
	ActiveCount    int              `json:"-"`              // count of !done
	CompletedCount int              `json:"-"`              // count of done
}

// NewTodoAppProps creates TodoAppProps from TodoAppInput.
func NewTodoAppProps(in TodoAppInput) TodoAppProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoApp_" + randomID(6)
	}

	return TodoAppProps{
		ScopeID: scopeID,
		InitialTodos: in.InitialTodos,
		Todos: nil,
		NewText: "",
		Filter: "all",
		HashListenerAdded: false,
	}
}
