package main

import (
	"html/template"
	"io"
	"net/http"
	"strings"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// CounterProps represents the props for the Counter component.
// Generated by @barefootjs/go-template adapter.
type CounterProps struct {
	ScopeID string
	Initial int
	Count   int
	Doubled int
}

// Template renderer for Echo
type TemplateRenderer struct {
	templates *template.Template
}

func (t *TemplateRenderer) Render(w io.Writer, name string, data interface{}, c echo.Context) error {
	return t.templates.ExecuteTemplate(w, name, data)
}

func main() {
	e := echo.New()

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Load templates
	t := &TemplateRenderer{
		templates: template.Must(template.ParseGlob("dist/templates/*.tmpl")),
	}
	e.Renderer = t

	// Routes
	e.GET("/", indexHandler)
	e.GET("/counter", counterHandler)

	// Static files (for client JS)
	e.Static("/static", "dist")

	// Shared styles
	e.Static("/shared", "../shared")

	e.Logger.Fatal(e.Start(":8080"))
}

func indexHandler(c echo.Context) error {
	return c.HTML(http.StatusOK, `
<!DOCTYPE html>
<html>
<head>
    <title>BarefootJS + Echo Example</title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }
        h1 { color: #333; }
        a { color: #0066cc; }
    </style>
</head>
<body>
    <h1>BarefootJS + Echo Example</h1>
    <p>This example demonstrates server-side rendering with Go Echo and BarefootJS.</p>
    <ul>
        <li><a href="/counter">Counter Component</a></li>
    </ul>
</body>
</html>
`)
}

func counterHandler(c echo.Context) error {
	// Initial count value (could come from query param, database, etc.)
	initial := 0

	props := CounterProps{
		ScopeID: "Counter_1", // Must match pattern: ComponentName_instanceId
		Initial: initial,
		Count:   initial,
		Doubled: initial * 2,
	}

	// Wrap the component in a full HTML page
	return c.HTML(http.StatusOK, renderPage("Counter", props))
}

func renderPage(componentName string, props interface{}) string {
	t := template.Must(template.ParseGlob("dist/templates/*.tmpl"))

	// Create a page template that includes the component
	pageHTML := `
<!DOCTYPE html>
<html>
<head>
    <title>` + componentName + ` - BarefootJS + Echo</title>
    <link rel="stylesheet" href="/shared/styles/components.css">
    <style>
        body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }
    </style>
</head>
<body>
    <h1>` + componentName + ` Component</h1>
    <div id="app">`

	// Render the component
	var buf strings.Builder
	buf.WriteString(pageHTML)

	t.ExecuteTemplate(&buf, componentName, props)

	buf.WriteString(`</div>
    <p><a href="/">← Back to index</a></p>

    <script type="module" src="/static/client/` + componentName + `.client.js"></script>
</body>
</html>`)

	return buf.String()
}
